---
abstract: 'Configuration files for Clustericious nodes.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::HomeDir::Test: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Config
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Exporter: 0
  File::HomeDir: 0
  File::Path: 0
  Hash::Merge: 0
  JSON::XS: 0
  List::Util: 0
  Log::Log4perl: 0
  Module::Build: 0.3601
  Mojolicious: 3.85
  Path::Class: 0.26
  Storable: 0
  Sys::Hostname: 0
  Term::Prompt: 0
  Test::Builder::Module: 0
  YAML::XS: 0
  base: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/clustericious-config/issues
  homepage: http://perl.wdlabs.com/Clustericious-Config/
  repository: git://github.com/plicease/clustericious-config.git
version: 0.30
