---
abstract: 'Configuration for clustericious clients or servers'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires:
  File::HomeDir: 0.91
  Hash::Merge: 0
  JSON::XS: 0
  Log::Log4perl: 0
  Module::Build: 0.36
  Mojolicious: 1.01
  Term::Prompt: 0
  Test::More: 0
  YAML::XS: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Config
no_index:
  directory:
    - share
    - util
provides:
  Clustericious::Config:
    file: lib/Clustericious/Config.pm
    version: 0.20
  Clustericious::Config::Password:
    file: lib/Clustericious/Config/Password.pm
    version: 0.20
  Clustericious::Config::Plugin:
    file: lib/Clustericious/Config/Plugin.pm
    version: 0.20
  Test::Clustericious::Config:
    file: lib/Test/Clustericious/Config.pm
    version: 0.20
resources:
  bugtracker: https://github.com/plicease/Clustericious-Config/issues
  homepage: http://perl.wdlabs.com/Clustericious-Config
  license: http://dev.perl.org/licenses/
  repository: git://github.com/plicease/Clustericious-Config.git
version: 0.20
